name: memoquiz
description: Memo + AI quiz (desktop)
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^11.4.2
  intl: any
  path: ^1.9.0
  path_provider: ^2.1.3
  http: ^1.2.2
  json_annotation: ^4.9.0
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.18.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
